import numpy as np


class thruster:
    """
    Represents a thruster for hydrodynamic calculations.

    INPUTS:
        rho:    density of fluid (kg/m^3)

    Coordinate system: Right-handed, x-forward, y-starboard, z-down
    """

    def __init__(self, rho):
        # Actuator dynamics
        self.nMax = 1525  # max propeller revolution (rpm)
        self.T_n = 0.1  # propeller time constant (s)
        self.u_actual_n = 0.0  # actual rpm of the thruster
        self.rho = rho

    def tau(self, nu_r, nu):
        """
        Calculate force vector generated by the fin.

        Parameters:
            nu_r (numpy array): Relative velocity [vx, vy, vz, p, q, r]
                              (m/s for linear, rad/s for angular)
            nu (numpy array): Velocity [vx, vy, vz, p, q, r]
                              (m/s for linear, rad/s for angular)

        Returns:
            numpy array: tau vector [Fx, Fy, Fz, Tx, Ty, Tz] (N) and (N*m) in body-fixed frame
        """
        U = np.sqrt(nu[0] ** 2 + nu[1] ** 2 + nu[2] ** 2)  # vehicle speed

        # Commands and actual control signals
        n = self.u_actual_n  # actual propeller revolution (rpm)

        # Amplitude saturation of the control signals
        if abs(n) >= self.nMax:
            n = np.sign(n) * self.nMax

        # Propeller coeffs. KT and KQ are computed as a function of advance no.
        # Ja = Va/(n*D_prop) where Va = (1-w)*U = 0.944 * U; Allen et al. (2000)
        D_prop = 0.14  # propeller diameter corresponding to 5.5 inches
        t_prop = 0.1  # thrust deduction number
        n_rps = n / 60  # propeller revolution (rps)
        Va = 0.944 * U  # advance speed (m/s)

        # Ja_max = 0.944 * 2.5 / (0.14 * 1525/60) = 0.6632
        Ja_max = 0.6632

        # Single-screw propeller with 3 blades and blade-area ratio = 0.718.
        # Coffes. are computed using the Matlab MSS toolbox:
        # >> [KT_0, KQ_0] = wageningen(0,1,0.718,3)
        KT_0 = 0.4566
        KQ_0 = 0.0700
        # >> [KT_max, KQ_max] = wageningen(0.6632,1,0.718,3)
        KT_max = 0.1798
        KQ_max = 0.0312

        # Propeller thrust and propeller-induced roll moment
        # Linear approximations for positive Ja values
        # KT ~= KT_0 + (KT_max-KT_0)/Ja_max * Ja
        # KQ ~= KQ_0 + (KQ_max-KQ_0)/Ja_max * Ja

        if n_rps > 0:  # forward thrust
            X_prop = (
                self.rho
                * pow(D_prop, 4)
                * (
                    KT_0 * abs(n_rps) * n_rps
                    + (KT_max - KT_0) / Ja_max * (Va / D_prop) * abs(n_rps)
                )
            )
            K_prop = (
                self.rho
                * pow(D_prop, 5)
                * (
                    KQ_0 * abs(n_rps) * n_rps
                    + (KQ_max - KQ_0) / Ja_max * (Va / D_prop) * abs(n_rps)
                )
            )

        else:  # reverse thrust (braking)
            X_prop = self.rho * pow(D_prop, 4) * KT_0 * abs(n_rps) * n_rps
            K_prop = self.rho * pow(D_prop, 5) * KQ_0 * abs(n_rps) * n_rps

        # Thrust force vector
        # K_Prop scaled down by a factor of 10 to match exp. results
        tau_thrust = np.array([(1 - t_prop) * X_prop, 0, 0, K_prop / 10, 0, 0], float)
        return tau_thrust

    def actuate(self, sampleTime, command):
        # Actuator dynamics
        n_dot = (command - self.u_actual_n) / self.T_n

        self.u_actual_n += sampleTime * n_dot

        return self.u_actual_n
