[project]
name = "thesis"
version = "1.0.0"
description = "Repository of the TUDelft MSc Marine Technology thesis: Efficient Probabilistic Forecasting of Dynamic Positioning Behaviour" 
authors = [{ name = "Albert Aperghis", email = "a.w.n.aperghis@student.tudelft.nl" }]
requires-python = ">=3.11,<3.14"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
package-mode = true
dependencies = [
    "arch>=8.0.0",
    "casadi>=3.7.2",
    "diffrax>=0.7.0",
    "equinox>=0.13.4",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jaxtyping>=0.3.7",
    "matplotlib>=3.10.8",
    "mlflow>=2.19",
    "numpy>=2.4.1",
    "optax>=0.2.7",
    "optimistix>=0.0.11",
    "pandas>=2.3.3",
    "pyarrow>=4.0.0",
    "pypdf>=6.7.5",
    "scikit-learn>=1.7.2",
    "statsmodels>=0.14.6",
    "tqdm>=4.67.3",
    "ty>=0.0.54",
]

[tool.uv]
package = true
default-groups = ["cuda", "torch"]
conflicts = [
    [
        { group = "cpu" },
        { group = "cuda" },
        { group = "amd"}
    ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128"},
]
torchvision = [
  { index = "pytorch-cu128"},
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[build-system]
requires = ["uv_build>=0.9.11,<=0.10.9"]
build-backend = "uv_build"



[dependency-groups]
dev = [
    "tensorboard>=2.20.0",
    "pytest>=8.0",
    "xprof>=2.22.0",
    "snakeviz>=2.2.2",
    "ruff>=0.15.0",
    "nvidia-ml-py>=13.590.48",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.3",
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-literate-nav>=0.6.3",
    "ipykernel>=7.2.0",
    "pip-licenses>=5.5.5",
    "license-audit>=0.12.1",
]
cpu = ["jax>=0.9.0",
      {include-group = "dev"}]

cuda = [
    "jax[cuda12]>=0.9.0; sys_platform != 'win32'",
    "jax>=0.9.0; sys_platform == 'win32'",
    {include-group = "dev"}
]
amd = [
    "jax[rocm7-local]>=0.9.0; sys_platform != 'win32'",
    "jax>=0.9.0; sys_platform == 'win32'",
    {include-group = "dev"}
]


torch = [
    "torch>=2.10.0",
    "torchsde>=0.2.6",
    "torchvision>=0.25.0",
]

[project.optional-dependencies]
cpu = ["jax>=0.9.0"]
cuda = [
    "jax[cuda12]>=0.9.0; sys_platform != 'win32'",
    "jax>=0.9.0; sys_platform == 'win32'",
  ]
torch = [
    "torch>=2.10.0",
    "torchsde>=0.2.6",
    "torchvision>=0.25.0",
  ]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-v", "--tb=short"]

[tool.ruff.lint]
ignore = ["E731"]

[tool.ruff]
exclude = ["*.ipynb"]

